### ISSUE TITLE
a question about the actors

### ISSUE THREAD

**Issue by stefan2410** [paolosalvatori/servicefabricasynchronouscomputingactors#1]
Hi, thanks for your fantastic work.
I've a question about the actors in the [WorkerActorService](https://github.com/paolosalvatori/servicefabricasynchronouscomputingactors/blob/master/WorkerActorService/Program.cs#L48).  The three actor services run in the same process or each one in their process, so they will have a serialization's cost in their interaction?
I read that they run in[ separated processes](https://stackoverflow.com/questions/37146843/how-can-i-host-multiple-service-fabric-actor-types-inside-a-single-service/37148990#37148990) actually. 
If I initialize a singleton object (with read-only properties, expensive to be created in instances)  in Main, then I can use it in my single actor's type instances (at least for those running in the same node, I don't mind if the singleton is recreated in another node). How does it work if the different actor types run in separate processes?
thanks!

**Comment by paolosalvatori** [comment]
Hi @stefan2410, thanks for the positive feedback. I initially created and configured the 3 actor services to run in the same host process as I wanted to adopt service affinity to run worker, queue and processor actors with the same id in the same process. However, service affinity does not currently support stateful reliable and actor services with multiple partitions. So service affinity works only when configuring the 3 services to use a single partition. At this time, the 3 services run in the same host process, right, but even if they are configured to use the same number of partitions, partitions are not aligned. In other words, the worker, queue and processor actor sharing the same actor id, could potentially run in different host processes on different cluster nodes, unless you configure all services to use service affinity and a single partition. Hope this helps!

**Comment by stefan2410** [comment]
Thank you,
I did not know that "to run worker, queue and processor actors with the same id in the same process.". neither I tested the service affinity (it is new for me) in my project. You are using Custom Service, I'd thought to do the same.   I should read and test much more. I would like to ask you again after my testing.
The "same id", you probably mean that actors can have the same id and the actor proxy will find them from the type. e.g.  ActorProxy.Create<  IFieldActor  >(new ActorId(deviceId)...    This can keep them in the same host process but there is not warranty for the actual alignment..

**Comment by paolosalvatori** [comment]
Yep, I mean that if you look at my code, at least when processing messages in a sequential order, the worker, queue and processor actor share the same ActorId(id). Let's say you use 3 partitions for the 3 services and let's call them A, B and C. Each partition represents a range of ids between lnt64.MinValue and Int64.MaxValue. Let's say you have a cluster with just 3 nodes. Let's assume you host the 3 services in the same host process, and that with XYZ I indicate the partitions, respectively of the worker, queue and processor actor service. You may end up in a situation like this:
 
 - ABC
 - BCA
 - CAB

I hope I represented the situation the right way.
