### ISSUE TITLE
a question about the StateManager

### ISSUE THREAD

**Issue by stefan2410** [paolosalvatori/servicefabricasynchronouscomputingactors#2]
Hi,
please a question (naive maybe?) for the StateManager in persisted actors.
If I save only  the state repeatedly during actor's lifecycle and retrieve it in actor's activation,   as I keep it also in memory,  should await the StateManager?  
Does it raise exceptions, or in case of its failure (saving in replicas), the enviroment would provoke actor's deactivation?
 If I don't await to complete,  would scheduler  send next turn to actor (desirable)? maybe a possible problem could be, if StateManager had not finished the serialization, before save?  I care about performance, when the state is big in size.
Thank you.

**Comment by paolosalvatori** [comment]
Hi @stefan2410 is there any particular reason for not awaiting the StateManager to retrieve the state during actor activation?

**Comment by stefan2410** [comment]
@paolosalvatori  during actor activation always await to retrieve the state.
My question is when we call the .SetStateAsync. .In case that the state is a  list or dictionary in local memory ,   it will save it  as a  whole.  For example a queue of pending  messages (variable sizes). I know the best is to save each message, but it is a requirement.

**Comment by paolosalvatori** [comment]
@stefan2410 if you look at https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-actors-state-management you can also return the task resulting from the call to SetStateAsync:

[StatePersistence(StatePersistence.Persisted)]
class MyActor : Actor, IMyActor
{
    public MyActor(ActorService actorService, ActorId actorId)
        : base(actorService, actorId)
    {
    }

    public Task SetCountAsync(int value)
    {
        return this.StateManager.SetStateAsync<int>("MyState", value);
    }
}

**Comment by stefan2410** [comment]
@paolosalvatori  the actor service's job scheduler would send next turn of work in the actor, before the StateManager complete its operation?  I will do tests myself.
e.g with C# 7 discards           _=this.StateManager.SetStateAsync<int>("MyState", value);
By the way, the IActorStateManager.GetStateNamesAsync(CancellationToken)  retrieves  all the keys (state names), in case I save each message with its unique key?
Thank you!  I learn a lot from your projects.

**Comment by paolosalvatori** [comment]
Thanks for the positive feedback @stefan2410 :)
